remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [Jakarta WebSockets]
description: [Jakarta WebSockets Implementation]

links:
  source: https://github.com/eclipse-ee4j/websocket-api
  javadocs: docs/api/
  issues_url: site.github.issues_url
  download: https://github.com/eclipse-ee4j/websocket-api/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/websocket-dev
  # faq: FAQ

include:
  - LICENSE.md
  - CONTRIBUTING.md

